### ISSUE TITLE
Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37

### ISSUE THREAD

**Issue by soldier14** [duckdb/duckdb-java#7]
Hi, I got some issue when ran on Jenkins pipeline (amazoncorretto:17-alpine-jdk) but on my mac M2 it worked well. I use duckdb_jdbc version 0.10.0
`Failed to map supported failure 'org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java18431916939631373028.so: Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@4ebaa179': Cannot invoke "Object.getClass()" because "obj" is null
`

this is how I get connection
```
fun getConnection(): Connection {
    val connectionProperties = Properties()
    connectionProperties.setProperty("temp_directory", "/path/to/temp/dir/")
    return DriverManager.getConnection("jdbc:duckdb:", connectionProperties)
  }
```

what I've tried so far?
I installed gcompat there's no more issue with /lib/ld-linux-x86-64.so.2  but I encountered another one
```
java.sql.SQLException: Invalid Error: No error information
    at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
    at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)
    at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
    at au.com.originenergy.cds.repository.DuckDBRepository.getConnection(DuckDBRepository.kt:17)
    at au.com.originenergy.cds.service.DuckDBService.processOutcomes(DuckDBService.kt:15)
    at au.com.originenergy.cds.service.ParquetFileService.processOutcomes(ParquetFileService.kt:18)
    at au.com.originenergy.cds.service.ParquetFileServiceTest.should generate parquet files from outcomes(ParquetFileServiceTest.kt:29)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

My EC2 instance OS info in Jenkins is 
```
17:36:19  + echo 'OS Information:'
17:36:19  OS Information:
17:36:19  + cat /etc/os-release
17:36:19  NAME="Amazon Linux"
17:36:19  VERSION="2"
17:36:19  ID="amzn"
17:36:19  ID_LIKE="centos rhel fedora"
17:36:19  VERSION_ID="2"
17:36:19  PRETTY_NAME="Amazon Linux 2"
17:36:19  ANSI_COLOR="0;33"
17:36:19  CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
17:36:19  HOME_URL="https://amazonlinux.com/"
17:36:19  SUPPORT_END="2025-06-30"
17:36:19  + echo 'Kernel Information:'
17:36:19  Kernel Information:
17:36:19  + uname -a
17:36:19  Linux ip-10-204-36-231.ap-southeast-2.compute.internal 4.14.336-257.562.amzn2.x86_64 #1 SMP Sat Feb 24 09:50:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
17:36:19  + echo 'LSB Release Information:'
17:36:19  LSB Release Information:
17:36:19  + lsb_release -a
17:36:19  + echo 'lsb_release not installed'
17:36:19  lsb_release not installed
```

Could you please help me take a look? Many thanks.

**Comment by Mause** [comment]
As discussed on discord, we don't support alpine/musl
