### ISSUE TITLE
Attemped it dereference unique_ptr that is null

### ISSUE THREAD

**Issue by Stongtong** [duckdb/duckdb-java#78]
hi guys:
    I meet this problem in my practice and confused a little, I use java call it ( java version is jdk 11 and duck db version is 1.0.0),   the detail log is below:

> Caused by: java.sql.SQLException: FATAL Error: Failed: database has been invalidated because of a previous fatal error. the database must be restarted prior to being used again.
Original error: "Failed: database has been  invalidated because of a previous fatal error. the database must be restarted prior to being used again.
Original error: "Failed: database has been  invalidated because of a previous fatal error. the database must be restarted prior to being used again.
Original error: "Failed: database has been  invalidated because of a previous fatal error. the database must be restarted prior to being used again.
Original error: "Attemped it dereference unique_ptr that is NULL!""""
at org.duckdb.DuckDBNative.duckdb_jdbc_execute(Native Method)
at org.duckdb.DuckDBPrepareStatement.execute(DuckDBPrepareStatement.java:143)
at org.duckdb.DuckDBPrepareStatement.execute(DuckDBPrepareStatement.java:197)

**Comment by Mause** [comment]
Can you please provide steps to reproduce this issue?

**Comment by staticlibs** [comment]
@Stongtong 

Hi! Thanks for the report! Just the message about "dereferencing unique_ptr" is a generic error message and only Java stacktrace is printed in such case - native stacktrace not available in release builds and it is really hard to tell where the error could have happened without it. I will close this as "cannot reproduce", please feel free to re-open with any details if the issue keep happening.
